project:
  type: website
  output-dir: docs
website:
  back-to-top-navigation: true
  google-analytics:
    storage: none
    tracking-id: G-VM5FZERPPB
  navbar:
    left:
      - icon: house
        url: index.html
      - href: tr_ekon.html
        text: Türkiye Ekonomisi
      - href: blog.html
        text: Blog
      - href: cv.html
        text: CV
    right:
      - icon: envelope-fill
        url: mailto:ismet.asci@outlook.com
      - icon: twitter
        url: https://twitter.com/a_ismet_asci
      - icon: linkedin
        url: https://www.linkedin.com/in/ismetasci/
      - icon: github
        url: https://github.com/aiasci
      - href: ../en
        text: EN
  page-footer:
    left: |
      <b>Anıl İsmet AŞCI</b> <br>
      © Aksi belirtilmedikçe her hakkı yazara saklıdır.
    right:
      - icon: envelope-fill
        url: mailto:ismet.asci@outlook.com
      - icon: twitter
        url: https://twitter.com/a_ismet_asci
      - icon: linkedin
        url: https://www.linkedin.com/in/ismetasci/
      - icon: github
        url: https://github.com/aiasci

format:
  html:
    theme: tema.scss
    css: styles.css
    toc: true



