project:
  type: website

website:
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Anasayfa
      - href: tr_ekon.qmd
        text: Türkiye Ekonomisi
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV
    right:
      - icon: twitter
        url: https://twitter.com/a_ismet_asci
      - icon: linkedin
        url: https://www.linkedin.com/in/ismetasci/
      - icon: github
        url: https://github.com/aiasci
      - href: en.qmd
        text: EN
  page-footer:
    left: |
      <b>Anıl İsmet AŞCI</b> <br>
      © Aksi belirtilmedikçe her hakkı yazara saklıdır.
    right:
      - icon: twitter
        url: https://twitter.com/a_ismet_asci
      - icon: linkedin
        url: https://www.linkedin.com/in/ismetasci/
      - icon: github
        url: https://github.com/aiasci

format:
  html:
    theme: tema.scss
    css: styles.css
    toc: true



