---
title: "Curriculum Vitae"
format:
  html:
    toc: true
  pdf:
    author: A. İsmet AŞCI
format-links: [pdf]
---

::: {.no-print}
::: {style="text-align: justify;"}
Interested in economics, especially economic development and growth, monetary theory, and macroprudential policies. Also, proficient in data manipulation, analysis, and visualization along with econometric time-series analysis. Willing to work in economic research departments, NGOs, and data analysis departments
:::
:::


## SKILLS
::: {style="row"}
::: {style="float: left;  width: 50%;  padding: 5px;  height: 200px;"}
- MS OFFICE
- R 
    + Data Manipulation
    + Data Visualization
    + Web Scrapping
    + Text Analysis
    + [Shiny Apps](aiasci.shinyapps.io/searcher/)
:::
::: {style="float: left;  width: 50%;  padding: 5px;  height: 200px;"}
- Python
    + Data Manipulation
    + Data Visualization
    + Web Scrapping
    + Text Analysis
    + Geospatial Analysis
:::
:::

<br>

## LANGUAGES

::: {style="row; text-allign: center;width: 100%;"}
::: {style="float: left;  width: 50%;  padding: 5px;  height: 100px;"}
- Turkish Native
- Persian (A2)
:::    
::: {style="float: left;  width: 50%;  padding: 5px;  height: 100px;"}
- English
    + TOEFL IBT 94
:::
:::




## EDUCATION

**Master of Science -- Economics** <br> *Middle East Technical University*  [*Oct 2021 --- Present*]{.cvdate}

-   Analysing Turkish Real Sector using firm-level data provided by Ministry of Industry and Technology 
<br>

**Department of Economics** <br> *Middle East Technical University*   [*2015 --- 2021*]{.cvdate}

## WORK EXPERIENCE{style="page-break-before: always"}

### Research Associate

***The Economic Policy Research Foundation of Turkey (TEPAV)*** [Sep 2021 -- Dec 2023]{.cvdate}

Generating datasets, data analysis, and reporting on local and international events that may affect the Turkish economy. Preparing plans regarding cooperation possibilities between Turkey and other countries. Producing reports for policy-makers, foreign governmental bodies/business organizations, NGOs, and local officials. In addition to the day-to-day workload I have also participated in projects included:

-  **Turkish Economic Outlook**:
    + I was part of a team that produced monthly reports on the Turkish Economic Outlook with selected indicators such as economic growth, production, and sales; foreign trade and balance of payments; employment; public finances; inflation; and financial market indicators.
-  **UNDP - Afghanistan Project**:
    + After the Taliban takeover in Afghanistan, I worked as a junior economic expert in Afghanistan’s private sector-led development and reported on challenges to women entrepreneurs with UNDP, IICPSD, and TEPAV. <br>
    +  I helped to identify private sector-led development possibilities, by using export data as a proxy for production along with the methodology of Harvard Growth's Lab then I differentiated the sectors by using GIS. Lastly, I studied the need for institutional frameworks to implement the project.
-  **GIZ - Istanbul Project**:
    + I was part of a research team for planning Istanbul's food system which BMZ funds and carried out by GIZ, IPA, and TEPAV.<br>
    + As a team, we focused on two aspects, where does Istanbul receive its food from and how does the national food system affect food prices?  In three meetings, we shared our research on this issue with our stakeholders in the food sector, IPA and GIZ, and tried to prepare a common action plan.
-  **GIZ - Gaziantep Project**:
    + I was a part of the research and planning team for Gaziantep Industrial Zone’s Green Transition Project which is funded by BMZ and carried out by GIZ, Gaziantep Metropolitan Municipality, and TEPAV.
-  **Jenin IFZ Project**:
    + I was part of a team working on the handover process of the Jenin Industrial Free Zone, on the Northern tip of the West Bank, from BMZ to UCCET (TOBB).
-  **Eurochambres SME Surveys Project**:
    +  I was part of a team that designed and analyzed SME surveys in Turkey and the EU for Turkey-EU business dialogue conferences which are conducted by Eurochambres and UCCET (TOBB).
-  **Turkish Earthquake Study**:
    + I was part of the team that studied the impact of the recent earthquake on the Turkish economy and possible policy frameworks regarding that. <br>
    + I collaborated with the team to create and analyze the needed statistics for the earthquake region. By using web scrapping we developed a tool for the most recent destroyed and damaged building statistics. Two reports on this issue were published by TEPAV. 


::: {.print-only}
## References
Available upon request
:::
